spring:
  mail:
    host: smtp.163.com #163\u90AE\u7BB1\u670D\u52A1\u5668\u5730\u5740
    username: -------@163.com #\u7528\u6237\u540D
    password: ------- #\u5BC6\u7801
    default-encoding: UTF-8
  # \u8D85\u65F6\u65F6\u95F4
  properties:
    mail:
      smtp:
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000